export const EMPTY_BASKET = 'EMPTY_BASKET';
export const ADD_BASKET_ITEM = 'ADD_BASKET_ITEM';
export const REMOVE_BASKET_ITEM = 'REMOVE_BASKET_ITEM';

export const SET_CUSTOMER_FIELD = 'SET_CUSTOMER_FIELD';
export const SET_ORDER_NUMBER = 'SET_ORDER_NUMBER';
export const SET_DELIVERY_FIELD = 'SET_DELIVERY_FIELD';
export const SET_ADDRESS_FIELD = 'SET_ADDRESS_FIELD';

export const SET_ORDER_COMPLETE = 'ORDER_COMPLETE';
